name: name_bingo_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.5
  riverpod_annotation: ^2.3.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  riverpod_generator: ^2.3.5
  build_runner: ^2.4.6
  custom_lint: ^0.5.5
  riverpod_lint: ^2.3.3
  freezed: ^2.4.5
  json_serializable: ^6.7.1
flutter:
  uses-material-design: true

flutter_icons:
    android: true
    ios: true
    remove_alpha_ios: true
    image_path: "assets/icon.png"
    min_sdk_android: 21
    adaptive_icon_background: '#FFF422'
    adaptive_icon_foreground: "assets/icon.png"
    macos:
      generate: true
      image_path: "assets/icon.png"